GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/5e303bb55602e03d7c3207c8

###

# POST http://localhost:3000/subscribers

# Content-Type: application/json

# {
#   "name": "amazing Person",
#   "subscribedToChannel": "Web Dev Simplified"
# }

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Amazing Person",
    "subscribedToChannel": "Web Dev Simplified"
}

###
DELETE  http://localhost:3000/subscribers/5e30443e32e8ab0c7ccdc10c

###

PATCH  http://localhost:3000/subscribers/5e30443e32e8ab0c7ccdc10c
Content-Type: application/json

{
  "name": "new name"
}